### ISSUE TITLE
Add useDarkMode

### ISSUE THREAD

**Issue by JamesSingleton** [JamesSingleton/hooks-arsenal#16]
# 🚀  Feature Request

Add `useDarkMode`

## 🔦 Scope

New hook that enables or disables dark mode.

**Comment by JamesSingleton** [comment]
@igetgames how's this going?

**Comment by LoganArnett** [comment]
Is this up for grabs? I would like to work on it

**Comment by JamesSingleton** [comment]
@LoganArnett yup! Still up for grabs

**Comment by LoganArnett** [comment]
Perfect I will get started today

**Comment by LoganArnett** [comment]
@JamesSingleton I have opened my PR with the hook and tests for it, please let me know if there is anything else I can update or add to it
