### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by heythisispaul** [JamesSingleton/hooks-arsenal#260]
Is there any plan to include documentation for the hooks provided here?

I think it'd be helpful to get the word out!

**Comment by JamesSingleton** [comment]
@heythisispaul yeah I was thinking about adding https://v2.docusaurus.io/

**Comment by JamesSingleton** [comment]
@heythisispaul https://hooks-arsenal.vercel.app/ I just put the template up for it

**Comment by JamesSingleton** [comment]
@heythisispaul do you mind adding documentation for the hooks that you added?

**Comment by LoganArnett** [comment]
@JamesSingleton I added a PR for the DarkMode hooks, I can add to that PR or create another with the other hooks with usage examples

**Comment by JamesSingleton** [comment]
@LoganArnett I will look at the current PR and then if you want to add docs for the others, they can be added in another PR

**Comment by heythisispaul** [comment]
@JamesSingleton I also opened a PR to add docs for my hooks as well: #277 🥳

**Comment by JamesSingleton** [comment]
@heythisispaul I think we have addressed most of the documentation. Do you want to keep this open or close it?

**Comment by heythisispaul** [comment]
@JamesSingleton I'm ready to shut it down if you are 👍
